image: atlassian/default-image:4

pipelines:
  branches:
    main:
    - step:
        name: Deploy to Production
        deployment: production
        runs-on:
          - self.hosted
          - linux
        script:
          - pipe: ggoisset/google-app-engine-deploy:master
            variables:
              KEY_FILE: $KEY_FILE
              PROJECT: $PROJECT
              VERSION: '${BITBUCKET_BUILD_NUMBER}'
              PROMOTE: 'true'
              STOP_PREVIOUS_VERSION: 'true'
              DEBUG: 'false'
